### PR TITLE
Added some "rought" way to install Nimble with nim-vm

### PR DESCRIPTION
**Pull request by oderwat**
This "should" work most of the time but will have problems with different shells and system configurations. But maybe better than nothing for the "average" user.

### CODE REVIEW

**Comment by andreaferretti** [comment]
@ekarlso This is very useful, especially for people that are beginners to Nim. Any chance you could incorporate this?

**Comment by andreaferretti** [comment]
@oderwat It seems that @ekarlso is not interested in keeping this up to date. Maybe you could update the 0tt0matic scripts and the README to point to your own fork, so that people can go to oderwat/nim-vm directly :-)

Every time I have to help someone install Nim, I have to direct them to your fork, then manually download the script, and so on. It would be much easier to tell them that oderwat/nim-vm is the new home of nim-vm and that it just works! ;-)

**Comment by andreaferretti** [comment]
@ekarlso @oderwat I am sorry to keep pushing, but is there a chance either
- this PR could be merged, or
- the oderwat branch could become the "official" nim-vm?

If you are not interested in keeping this up to date anymore, please at least let me know :-)

**Comment by oderwat** [comment]
@andreaferretti That modification is kind of a rough hack. I don't want to be responsible for it to work everywhere. Same goes for nim-vm itself. I love to use it and it works pretty well for what I need it but I don't really want to take responsibility for it.

**Comment by andreaferretti** [comment]
@oderwat Thank you for your reply! I am not an expert in bash, but I am thinking about forking it myself. Nimble is pretty crucial to work with Nim, and not being able to direct people to a single repo, rather going to a PR to find a fork, manually downloading the file, setting permissions and so on is not a good advertisement for newcomers...

**Comment by oderwat** [comment]
Yes, but that is imho not the original target for nim-vm. Nim-VM should make it easier to install _different_ versions of the compiler and keep them updated. Installing Nimble should be part of "Nim" itself and may be part of nim-vm in the means of running the script to install nimble from the actual release. 

What the script currently does to install Nimble is just hiding git and creating profile entries (which are likely to fail easy). It does not even allow different versions of Nimble as it uses master hardcoded.

Nim-VM is a helper to automate more tedious stuff and actually is not even targeted to "beginners" per se. I know where you come from and I myself promote using nim-vm over a "homebrew" install. 

I even use it on my linux machines because it is convenient and I have more control. But then.. it is just a bash based script. The installation instruction downloads code from the internet and runs that. I am not sure if one should likely taking responsibility for it :)

EDIT: Creating a forge for friends / co-workers is one thing. Creating a forge for the public is something else.

**Comment by andreaferretti** [comment]
The fact is that Nim is evolving continously, so one needs a way to upgrade in any case. Since the homebrew recipe is not mantained and Nim is not in any Linux repo that I know of, the only method right now is installing from source. This, imo, creates too much friction for beginners.

Installing Nim without Nimble is not very useful, and again, the only other way to install Nimble is from source.

I would rather not mantain nim-vm, but the installer situation right now is bad PR for Nim

**Comment by oderwat** [comment]
Well if you use homebrew you can install from source (devel) by `brew install nim --HEAD`. I also learned that Nim is in ArchLinux. Still your points are valid ... but this is what the Nim repository should solve. Not a foreign tool to maintain multiple versions of the Nim compiler. If at all, Nim-VM should be part of the Nim repository itself. I talked about this to @araq briefly in the past already. I think it is neither your nor mine, not even ekalso's thing to fix the installation situation for OSX and Linux (by offering a fork of what we think is the right version of nim-vm).

Edit: Actually there is even a Debian package for Nim https://wiki.debian.org/Nim .. and they have Packaging Nimble on their todo.

**Pull request closed without merging**
